export const ScalarType = new Set([
    "TypeID",
    "TypeInt",
    "TypeFloat",
    "TypeString",
    "TypeBoolean",
    "TypeObject",
    "TypeDate",
    "TypeEmail",
    "TypeDomain",
    "TypeIPv4",
    "Date",
    "string",
    "number",
    "boolean",
    "symbol",
    "undefined",
]);
